import type { DashboardData } from "./types";

/**
 * Mock dashboard payload. Replace this function with an API/DB fetch later;
 * the Dashboard UI only depends on `DashboardData`.
 */
export function getDashboardMockData(): DashboardData {
  return {
    stats: [
      {
        id: "total-leads",
        label: "Total Leads",
        value: 248,
        hint: "+18 this week",
        icon: "leads",
      },
      {
        id: "calls-today",
        label: "Calls Today",
        value: 36,
        hint: "12 still queued",
        icon: "calls",
      },
      {
        id: "completed-calls",
        label: "Completed Calls",
        value: 182,
        hint: "73% connect rate",
        icon: "completed",
      },
      {
        id: "interested",
        label: "Interested Leads",
        value: 54,
        hint: "Warm pipeline",
        icon: "interested",
      },
      {
        id: "follow-ups",
        label: "Follow-ups",
        value: 29,
        hint: "Due in next 48h",
        icon: "followups",
      },
      {
        id: "appointments",
        label: "Appointments",
        value: 17,
        hint: "8 this week",
        icon: "appointments",
      },
      {
        id: "conversion",
        label: "Conversion Rate",
        value: "21.8%",
        hint: "+2.4% vs last month",
        icon: "conversion",
      },
    ],
    recentCalls: [
      {
        id: "rc-1",
        callId: "call_8f2a1c",
        leadId: "lead_riya",
        customer: "Riya Sharma",
        phone: "+91 98765 43210",
        callStatus: "Completed",
        leadStatus: "Interested",
        duration: "4m 32s",
        date: "Today, 10:24 AM",
        dateIso: "2026-09-17T10:24:00+05:30",
        summary:
          "Asked about JEE crash course fees and batch timings. Requested a counselor callback tomorrow evening.",
        agentName: "Priya — Admissions",
      },
      {
        id: "rc-2",
        callId: "call_3b91de",
        leadId: "lead_arjun",
        customer: "Arjun Mehta",
        phone: "+91 98111 22003",
        callStatus: "In Progress",
        leadStatus: "New",
        duration: "1m 08s",
        date: "Today, 10:11 AM",
        dateIso: "2026-09-17T10:11:00+05:30",
        summary: "Live conversation in progress about NEET foundation program.",
        agentName: "Asha — Outreach",
      },
      {
        id: "rc-3",
        callId: "call_c0ee44",
        leadId: "lead_neha",
        customer: "Neha Kapoor",
        phone: "+91 97654 11882",
        callStatus: "Missed",
        leadStatus: "Follow-up",
        duration: "—",
        date: "Today, 9:48 AM",
        dateIso: "2026-09-17T09:48:00+05:30",
        summary: "No answer after two rings. Auto-scheduled retry for 6:00 PM.",
        agentName: "Priya — Admissions",
      },
      {
        id: "rc-4",
        callId: "call_77ad09",
        leadId: "lead_vikram",
        customer: "Vikram Singh",
        phone: "+91 99001 33445",
        callStatus: "Completed",
        leadStatus: "Converted",
        duration: "6m 15s",
        date: "Yesterday, 5:02 PM",
        dateIso: "2026-09-16T17:02:00+05:30",
        summary:
          "Confirmed enrollment for weekend batch. Demo class booked for Saturday 11 AM.",
        agentName: "Asha — Outreach",
      },
      {
        id: "rc-5",
        callId: "call_a19bf2",
        leadId: "lead_sana",
        customer: "Sana Qureshi",
        phone: "+91 98220 66771",
        callStatus: "Scheduled",
        leadStatus: "New",
        duration: "—",
        date: "Today, 2:30 PM",
        dateIso: "2026-09-17T14:30:00+05:30",
        summary: "Outbound call queued from September nurture campaign.",
        agentName: "Priya — Admissions",
      },
      {
        id: "rc-6",
        callId: "call_55e8c1",
        leadId: "lead_rohan",
        customer: "Rohan Patel",
        phone: "+91 98700 11223",
        callStatus: "Completed",
        leadStatus: "Not Interested",
        duration: "2m 41s",
        date: "Yesterday, 3:19 PM",
        dateIso: "2026-09-16T15:19:00+05:30",
        summary:
          "Already enrolled elsewhere. Asked not to be contacted for 60 days.",
        agentName: "Asha — Outreach",
      },
      {
        id: "rc-7",
        callId: "call_d2f601",
        leadId: "lead_meera",
        customer: "Meera Iyer",
        phone: "+91 98450 77889",
        callStatus: "Completed",
        leadStatus: "Follow-up",
        duration: "5m 03s",
        date: "Yesterday, 11:40 AM",
        dateIso: "2026-09-16T11:40:00+05:30",
        summary:
          "Interested in scholarship options. Will discuss with parents and confirm by Friday.",
        agentName: "Priya — Admissions",
      },
      {
        id: "rc-8",
        callId: "call_91bc33",
        leadId: "lead_kabir",
        customer: "Kabir Joshi",
        phone: "+91 97000 55667",
        callStatus: "Missed",
        leadStatus: "New",
        duration: "—",
        date: "Mon, 4:15 PM",
        dateIso: "2026-09-15T16:15:00+05:30",
        summary: "Busy tone. Added to evening retry window.",
        agentName: "Asha — Outreach",
      },
    ],
  };
}
